---
title: "06_figures_charts"
author: "Kolja Nenoff"
date: "2023-07-08"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
library(rstudioapi)
library(magrittr)
library(tidyverse)
library(data.table)
library(parallel)
library(dimRed)
library(devtools)
library(igraph)
library(energy)
library(ggrepel)
library(ggalt)
library(ggraph)
library(trend)
library(riverplot)
library(RANN)
library(RJSONIO)
library(RSpectra)
library(pcaMethods)
require(broom)
require(GGally)
require(ggpubr)
require(xgboost)
require(caret)
require(pdp)
require(iml)
require(data.table)
require(tidyverse)
```
```{r}
## set up path
DATA_DIR <- "../data/"
FIGURE_DIR <- "../figures/01_figures/"
WDI_DIR <- paste0(DATA_DIR, "WDI_data_230609/WDI_CSV")
RELATIVE_INDICATORS_FILE_NAME <- "01_data/relative_indicators_2023_06.R" # nolint
source("../libraries/01a_lib_social_indicators.R")

```
# data
```{r,Excess Mortility WHO Set}
excessCounrty_year<-read_excel("../data/230224_nature_WHO_excess_death/2022-03-25_covid-19_gem/WHO_COVID_Excess_Deaths_EstimatesByCountry.xlsx",sheet = 2)
excessCounrty_covariates<-read_excel("../data/230224_nature_WHO_excess_death/2022-03-25_covid-19_gem/WHO_COVID_Excess_Deaths_EstimatesByCountry.xlsx",sheet = 3)
excessRegion_year<-read_excel("../data/230224_nature_WHO_excess_death/2022-03-25_covid-19_gem/WHO_COVID_Excess_Deaths_EstimatesByRegion.xlsx",sheet = 2)
excessRegion_income<-read_excel("../data/230224_nature_WHO_excess_death/2022-03-25_covid-19_gem/WHO_COVID_Excess_Deaths_EstimatesByIncome.xlsx",sheet = 2)
excessRegion_income %>% group_by(income) %>% 
  summarise(p_value_mort=sum(excess.mean)/sum(expected.mean)*100,excess_comul=sum(excess.mean))
excessCounrty_year_pvalue<-excessCounrty_year %>% group_by(country,iso3,year) %>% 
  summarise(p_value_mort=sum(excess.mean)/sum(expected.mean)*100,excess_comul=sum(excess.mean))
excessCounrty_year %>% filter(year==2020)-> excessCounrty_year_2020
p_value_global_2020=sum(excessCounrty_year_2020$excess.mean,na.rm = T)/sum(excessCounrty_year_2020$expected.mean,na.rm = T)*100
excessCounrty_year %>% filter(year==2021)-> excessCounrty_year_2020
p_value_global_2021=sum(excessCounrty_year_2020$excess.mean,na.rm = T)/sum(excessCounrty_year_2020$expected.mean,na.rm = T)*100
excessCounrty_monthly_pvalue<-excessCounrty_year  %>% 
  mutate(p_value_mort=(excess.mean)/(expected.mean)*100)
```



#  Methods 
## a Compare ISO and PCA
```{r}

residual_sample_variances <- compute_if_no_file(
  get_data_file("residual_sample_variances.RDS"),
  make_residual_variance_lists,
  qual_comp_res = qual_comp_res,
  wdi_data_cons_df = wdi_data_cons_df,
  used_var_names = USED_VAR_NAMES,
  .overwrite = TRUE
)



pca_res <- residual_sample_variances$pca
iso_res <- residual_sample_variances$iso
median_res_var_pca <- residual_sample_variances$median_pca
median_res_var_iso <- residual_sample_variances$median_iso
hdi_res_var <- residual_sample_variances$hdi
```
```{r}
plot(pca_res[[1]],
   ylim = c(0, max_res_var_1),
   ## xlim = c(1, max_dim),
   xlim = c(1, 10),
   ylab = "residual variance",
   xlab = "number of dimensions",
   cex.lab = 2,
   las = 1,
   xaxt = "n",
   yaxt = "n",
   bty = "n",
   type = "n")

points(wdi_data_qual_cons_pca,      type = "b",
     lwd = 4, col = lighten("slategrey", 0.8))
points(wdi_data_qual_cons_iso[[2]], type = "b",
     lwd = 4, col = lighten("seagreen", 0.8))
text(1, wdi_data_qual_cons_pca[1],      "PCA",
   pos = 4, offset = 0.5, xpd = TRUE, cex = 2)
text(1, wdi_data_qual_cons_iso[[2]][1], "Ensemble Isomap",
   pos = 4, offset = 0.5, xpd = TRUE, cex = 2)
text(max_x + 0.75,         0.1, "10% Residual Variance", cex = 1.8,
   adj = c(1.1, -0.5), xpd = TRUE)
abline(h = 0.1, col = "gray50", lwd = 2)
par(las = 1, mgp = c(1.5, 0.75, 0))#, xpd = TRUE)
axis(side = 1, at = 1:10, labels = ifelse(1:10 %% 2 == 1, 1:10, ""),
   col = "gray50", col.axis = "gray50",
   cex.axis = 1.5, lwd = 1, tcl = -0.25, lwd.ticks = 2)
axis(side = 2, at = seq(0, 1, length.out = 6),
   col = "gray50", col.axis = "gray50",
   cex.axis = 1.5, lwd = 1, tcl = -0.25, lwd.ticks = 2)
```
## b visualisation of  Nonlinearity

# Results
##  a Linear Estimation of Exmort
```{r}

dimred2021_knn250_2<-fread("../output/02_230612_Dimred_ExcessMort_annual.csv")
subset2020<-dimred2021_knn250_2 %>% filter(year%in% 2019) %>% select(year,iso1,iso2,iso3,iso4,iso5,iso6,iso7,iso8,iso9,iso10,year,P_mort_2020) %>% 
  rename(ExcessMort=P_mort_2020) %>% mutate(P_mort_2020=NULL)
subset2021<-dimred2021_knn250_2 %>% filter(year%in% 2020) %>% select(year,iso1,iso2,iso3,iso4,iso5,iso6,iso7,iso8,iso9,iso10,year,P_mort_2021) %>% 
  rename(ExcessMort=P_mort_2021) %>% mutate(P_mort_2020=NULL)
bothyears<-rbind(subset2020,subset2021)
e<-lm(scale(ExcessMort)~iso1+iso2+iso3+iso4+iso5+iso6+iso7,bothyears[]) 
e %>%  summary

# for each year
e1<-lm(ExcessMort~iso1+iso2+iso3+iso4+iso5+iso6+iso7+iso8+iso9+iso10,bothyears[] %>% filter(year%in% 2019))
e2<-lm(ExcessMort~iso1+iso2+iso3+iso4+iso5+iso6+iso7+iso8+iso9+iso10,bothyears[] %>% filter(year%in% 2020))
e1_rsquared<-round(summary(e1)$r.squared,digits = 3)*100
e2_rsquared<-round(summary(e2)$r.squared,digits = 3)*100
# 

 e_plot2020<-ggcoef_model(e1)+ ggtitle(paste0("Isomap 2020; R\u00b2: ",e1_rsquared," %"))%>% suppressWarnings()
 e_plot2021<-ggcoef_model(e2)+ ggtitle(paste0("Isomap 2021; R\u00b2: ",e2_rsquared," %")) %>%  suppressWarnings()
plotBoth<-ggarrange(e_plot2020,e_plot2021,common.legend = T,legend = "bottom") %>% suppressWarnings() 
#ggsave("../figures/06_figures_Beta_plot.png",device = "png")
# annotate_figure(plotBoth, top = text_grob("Estimated betas for Isomap 2020 and 2021", 
#                color = "Slategray3", face = "bold", size = 12),bottom = text_grob("asd"))

f<-lm(pscore_mean~iso1+iso2+iso3+iso4+iso5+iso6+iso7+iso8+iso9+iso10,dimred2021_knn250_2[] %>% filter(year%in% 2019))
f_rsquared<-round(summary(f)$r.squared,digits = 3)*100
f_plot_pscoremean<-ggcoef_model(f)+ ggtitle(paste0("P Score ~ ; R\u00b2: ",f_rsquared," %"))%>% suppressWarnings()
f_plot_pscoremean 
#%>% ggsave(file= "../figures/06_beta_plot_2019_pscore.png",device = "png",width = 5,height = 7)
```
##  a 2  Non Linear Estimation of Exmort

```{r}
thisData<-dimred2021_knn250_2[] %>% filter(year%in% 2019)
IsoYear<-"2019"
Label<-"pscore_mean"
candidates<-c("iso1","iso2","iso3","iso4","iso5","iso6","iso7")




param_grid <- expand.grid(
  nrounds = c(50),
  eta = c(0.05),
  max_depth = c(2, 4),
  colsample_bytree = c( 1),
  subsample = c(1),
  gamma = c(0),
  min_child_weight = c(0)
)
```


```{r message = F, warning = F}
thisData[thisData$year%in%IsoYear,] %>% select(Label,candidates) %>% drop_na() -> thisData_2
thisData_2 -> thisData_2_input
  ## create and test models

## test different parameters
xgb_caret <- caret::train(x = thisData_2_input %>% dplyr::select(candidates),
                   y = thisData_2_input %>% pull(Label),
                   method = "xgbTree",
                   verbosity = 0,

                   trControl=trainControl(method="cv",
                                          number = 6,
                                          search = "random",
                                          adaptive = list(
                                            alpha = 0.05,
                                            method = "BT", 
                                            complete = TRUE)
                                          ),tuneGrid = param_grid,
                   tuneLength = 2
                    # tuneGrid = expand.grid(nrounds = c(50, 100, 200),
                    #                       eta = c(0.01, 0.05, 0.1),
                    #                       max_depth = c(2, 4),
                    #                       colsample_bytree = c(0.6, 0.8, 1),
                    #                       subsample = c(0.6, 0.8, 1),
                    #                       gamma = c(0, 10, 50),
                    #                       min_child_weight = c(0, 10, 30))
                    )

finalmodel <- caret::train(x = thisData_2_input %>% dplyr::select(-Label, ),
                   y = thisData_2_input %>% pull(Label),
                   method = "xgbTree",
                   verbosity = 0,
                   ## CAST CV LLO (Hanna Meyer)
                   trControl=trainControl(method="cv",
                                          number = 30),
                   # early_stopping_rounds = 10,
                   tuneGrid = xgb_caret$bestTune)
finalmodel

```
```{r}

```


## b every month
```{r}
excessCounrty_monthly_pvalue 
merge(excessCounrty_monthly_pvalue,ExcessDimred[ExcessDimred$year%in% 2019,],by.x = "iso3",by.y="Country Code")-> thisdate 
thisdate %>% filter(!is.na(iso1))->thisdata2

lm(p_value_mort~iso3.y+iso1+iso2+iso4+iso5+iso6+iso7+iso8+iso9+iso10,thisdata2 %>% filter(year.x%in% 2020,month %in% 6)) %>%  summary

```
#### test if a dimension can predict the estimation methods

```{r}
a<-eval(parse(text = paste0("lm(pscore_mean~",paste(colnames(dimred2021_knn250_2)[6:12],collapse = " + "),",dimred2021_knn250_2[] %>% filter(year%in% 2019))")))
a %>%  summary
```


