---
title: "04_XgBoost"
author: "Kolja Nenoff"
date: "2023-06-12"
output:
  rmdformats::readthedown:
    code_folding: hide
    self_contained: true
    css: custom.css 
    lightbox: true
    gallery: true
    highlight: tango  
    toc_depth: 5
---

Now we need solid Xgboost results

# 0 Data and Methods
```{r,include=T,message=FALSE}
rm(list = ls())
require(xgboost)
require(caret)
require(pdp)
require(iml)
require(data.table)
require(tidyverse)
require(parallel)
require(broom)

```

```{r Load Excess Mort data}
ExcessDimred<-fread("../output/02_230612_Dimred_ExcessMort_annual.csv")
allcorr<-fread("../data/01_CorrWDI_dimred_10.csv")
colnames(allcorr)[2:11]<-paste(colnames(allcorr)[2:11],"_all",sep="")
```
# Xgboost rerun
## Setup

WDI 2019 for Exmort 2020 and WDI 2020 for Exmort 2021. First 7 Dimensions. both in one analysis. controlled by unsupervised cluster
```{r Subset for 2020 and 2021}


subset2020<-ExcessDimred %>% filter(year%in% 2019) %>% select(year,iso1,iso2,iso3,iso4,iso5,iso6,iso7,year,P_mort_2020) %>%
  rename(ExcessMort=P_mort_2020) %>% mutate(P_mort_2020=NULL)
subset2021<-ExcessDimred %>% filter(year%in% 2020) %>% select(year,iso1,iso2,iso3,iso4,iso5,iso6,iso7,year,P_mort_2021) %>%
  rename(ExcessMort=P_mort_2021) %>% mutate(P_mort_2020=NULL)

isos2020_2021<-rbind(subset2020,subset2021) %>%  na.omit()
isos2020_2021$year<-NULL
kmeans_result <- kmeans(scale(isos2020_2021[,c("iso1","iso2","iso3","iso4","iso5","iso6","iso7")]), centers = 6)
cluster_assignments <- kmeans_result$cluster
isos2020_2021$Kcluster <- cluster_assignments
candidates<-c("iso1","iso2","iso3","iso4","iso5","iso6","iso7")
```

```{r setup Cluster}
library(RhpcBLASctl)
RhpcBLASctl::omp_set_num_threads(30)


unregister_dopar <- function() {
  env <- foreach:::.foreachGlobals
  rm(list=ls(name=env), pos=env)
}
unregister_dopar()

param_grid <- expand.grid(
  nrounds = c(50),
  eta = c(0.05),
  max_depth = c(2, 4),
  colsample_bytree = c( 1),
  subsample = c(1),
  gamma = c(0),
  min_child_weight = c(0)
)
# 
# param_grid <- expand.grid(
#   nrounds = c(50, 100),
#   eta = c(0.01),
#   max_depth = c(2, 4)
# )
# ??expand.grid
# Define the custom training control with increased number of folds and parallel computation
custom_control <- trainControl(
  method = "cv",
  number = 30,  # Increase the number of folds
  search = "random",
  allowParallel = TRUE
  
)
?trainControl
custom_control

```

## Bootstrap subset
```{r trainingm,echo=FALSE}
trials <- 1000
thisplot_id<-1


for(i in 1:1000){
thisplot_id<-i

train_index <- sample(1:nrow(isos2020_2021), 0.8 * nrow(isos2020_2021))

data_input<-isos2020_2021[train_index,]

xgb_caret <- train(
    x = data_input %>% dplyr::select(-ExcessMort),
    y = data_input %>% pull(ExcessMort),
    method = "xgbTree",
    preProcess = "center",
    trControl = custom_control,tuneGrid = param_grid
  )
xgb_caret
finalmodel <- train(
  x = data_input %>% dplyr::select(-ExcessMort),
  y = data_input %>% pull(ExcessMort),
  method = "xgbTree",
  verbosity = 0,
  trControl = trainControl(method = "cv", number = 30),
  tuneGrid = xgb_caret$bestTune
)


thisResults<-finalmodel

RSME_value<-round(thisResults$results$RMSE,digits = 2)
Rsquared<-paste(round((thisResults$results$Rsquared)*100))
save_plotImot<-ggplot(varImp(thisResults)$importance %>%
         mutate(var = rownames(varImp(thisResults)$importance))%>%
         rename(importance = Overall)%>%
         filter(importance > 0))+
  geom_col(aes(
    x = importance,
    y = reorder(var, importance)
  ),
  fill = "Forestgreen") + ylab("")+ ggtitle(paste0("RMSE:\t",RSME_value,"  and ","R²:  ",paste(Rsquared,"% ", "")))


ggsave(save_plotImot,file = paste0("../test/importance_features/","important_features_",thisplot_id,".png"),device = "png")

pdp_all <- lapply(candidates, function(x){#
    pdp <- pdp::partial(finalmodel, pred.var = c(x), chull = TRUE)
    df <- pdp %>%
    gather(-yhat, key = key, value = value)
  })

pdp_all2<-do.call(rbind,pdp_all)

pdp_all2$RSME<-RSME_value
pdp_all2$Rsquared<-Rsquared
pdp_all2$run<-thisplot_id

pdp_plot<-pdp_all2 %>%   mutate(key = factor(key, levels=candidates)) %>%  ggplot(pdp_all2,
       mapping = aes_string(x = "value",
                           y = "yhat"))+
  geom_point()+
  geom_smooth(method = "loess", se=F)+
  theme_minimal()+
  facet_wrap(~(key), scales = "free", ncol = 3) 
ggsave(pdp_plot,file = paste0("../test/pdp_plots/","pdp_plot_",thisplot_id,".png"),device = "png")
fwrite(pdp_all2,file = paste0("../test/pdp_results/","pdp_results_",thisplot_id,".csv"))

fwrite(data.frame(TrainIndex=train_index),file = paste0("../test/trainindex/","trainindex_results_",thisplot_id,".csv"))
}
```

```{r}
pdpFrame<-data.frame()
for(i in 1:1000) {
  this<-fread(paste("../test/pdp_results/pdp_results_",i,".csv",sep=""))
  pdpFrame<-rbind(pdpFrame,this)
}
pdpFrame %>%ggplot(aes(x=RSME)) + geom_histogram()
pdpFrame$Rsquared %>%  summary
pdpFrame %>% filter(key%in% "iso4") %>%   mutate(key = factor(key, levels=candidates)) %>%  ggplot(pdpFrame,
       mapping = aes(x = value,
                           y = (yhat)))+
  geom_point()+
  geom_smooth(method = "loess", se=F)+
  theme_minimal()+
  facet_wrap(~(key), scales = "free", ncol = 3) 
```

test different R squared
## make differnt subsets for shapley

```{r}
### iso1
iso1_best25<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso1","yhat"])[5],"3rd Qu.:")))
iso1_best1<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso1","yhat"])[6],"Max.   :"))) 
treshold<-(iso1_best1+iso1_best25)/2
iso1cutoff<-pdpFrame %>% filter(key%in% "iso1",yhat>treshold) %>% summarise(name="iso1",min_value=min(value),max_value=max(value),Rsquared_mean=mean(Rsquared),Rsquared_var=var(Rsquared))
thiscutoff<-c(iso1cutoff$min_value,iso1cutoff$max_value)
isomap1cutoff_plot<-pdpFrame %>% filter(key%in% "iso1") %>%   mutate(key = factor(key, levels=candidates)) %>%  ggplot(pdpFrame,
       mapping = aes(x = value,
                           y = (yhat)))+
  geom_point(alpha=0.2)+
  geom_smooth(method = "loess", se=F)+
  theme_minimal()+geom_vline(xintercept = thiscutoff,size=2,color="firebrick4", linetype = "dashed")+xlab("Dimension 1")+ylab("PDP Value")
```


```{r}
### iso2
iso2_best25<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso2","yhat"])[5],"3rd Qu.:")))
iso2_best1<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso2","yhat"])[6],"Max.   :"))) 
treshold<-(iso2_best1+iso2_best25)/2
iso2cutoff<-pdpFrame %>% filter(key%in% "iso2",yhat>treshold) %>% summarise(name="iso2",min_value=min(value),max_value=max(value),Rsquared_mean=mean(Rsquared),Rsquared_var=var(Rsquared))


thiscutoff<-c(iso2cutoff$min_value,iso2cutoff$max_value)
isomap2cutoff_plot<-pdpFrame %>% filter(key%in% "iso2") %>%   mutate(key = factor(key, levels=candidates)) %>%  ggplot(pdpFrame,
       mapping = aes(x = value,
                           y = (yhat)))+
  geom_point(alpha=0.2)+
  geom_smooth(method = "loess", se=F)+
  theme_minimal()+geom_vline(xintercept = thiscutoff,size=2,color="firebrick4", linetype = "dashed")+xlab("Dimension 2")+ylab("PDP Value")

```


```{r}
### iso3
iso3_best25<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso3","yhat"])[5],"3rd Qu.:")))
iso3_best1<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso3","yhat"])[6],"Max.   :"))) 
treshold<-(iso3_best1+iso3_best25)/2
iso3cutoff<-pdpFrame %>% filter(key%in% "iso3",yhat>treshold) %>% summarise(name="iso3",min_value=min(value),max_value=max(value),Rsquared_mean=mean(Rsquared),Rsquared_var=var(Rsquared))

thiscutoff<-c(iso3cutoff$min_value,iso3cutoff$max_value)
isomap3cutoff_plot<-pdpFrame %>% filter(key%in% "iso3") %>%   mutate(key = factor(key, levels=candidates)) %>%  ggplot(pdpFrame,
       mapping = aes(x = value,
                           y = (yhat)))+
  geom_point(alpha=0.2)+
  geom_smooth(method = "loess", se=F)+
  theme_minimal()+geom_vline(xintercept = thiscutoff,size=2,color="firebrick4", linetype = "dashed")+xlab("Dimension 3")+ylab("PDP Value")

```


```{r}
### iso4
iso4_best25<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso4","yhat"])[5],"3rd Qu.:")))
iso4_best1<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso4","yhat"])[6],"Max.   :"))) 
treshold<-(iso4_best1+iso4_best25)/2
iso4cutoff<-pdpFrame %>% filter(key%in% "iso4",yhat>treshold) %>% summarise(name="iso4",min_value=min(value),max_value=max(value),Rsquared_mean=mean(Rsquared),Rsquared_var=var(Rsquared))


thiscutoff<-c(iso4cutoff$min_value,iso4cutoff$max_value)
isomap4cutoff_plot<-pdpFrame %>% filter(key%in% "iso4") %>%   mutate(key = factor(key, levels=candidates)) %>%  ggplot(pdpFrame,
       mapping = aes(x = value,
                           y = (yhat)))+
  geom_point(alpha=0.2)+
  geom_smooth(method = "loess", se=F)+
  theme_minimal()+geom_vline(xintercept = thiscutoff,size=2,color="firebrick4", linetype = "dashed")+xlab("Dimension 4")+ylab("PDP Value")

```


```{r}
### iso5
iso5_best25<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso5","yhat"])[5],"3rd Qu.:")))
iso5_best1<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso5","yhat"])[6],"Max.   :"))) 
treshold<-(iso5_best1+iso5_best25)/2
iso5cutoff<-pdpFrame %>% filter(key%in% "iso5",yhat>treshold) %>% summarise(name="iso5",min_value=min(value),max_value=max(value),Rsquared_mean=mean(Rsquared),Rsquared_var=var(Rsquared))


thiscutoff<-c(iso5cutoff$min_value,iso5cutoff$max_value)
isomap5cutoff_plot<-pdpFrame %>% filter(key%in% "iso5") %>%   mutate(key = factor(key, levels=candidates)) %>%  ggplot(pdpFrame,
       mapping = aes(x = value,
                           y = (yhat)))+
  geom_point(alpha=0.2)+
  geom_smooth(method = "loess", se=F)+
  theme_minimal()+geom_vline(xintercept = thiscutoff,size=2,color="firebrick4", linetype = "dashed")+xlab("Dimension 5")+ylab("PDP Value")

```
```{r}
### iso6
iso6_best25<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso6","yhat"])[5],"3rd Qu.:")))
iso6_best1<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso6","yhat"])[6],"Max.   :"))) 
treshold<-(iso6_best1+iso6_best25)/2
iso6cutoff<-pdpFrame %>% filter(key%in% "iso6",yhat>treshold) %>% summarise(name="iso6",min_value=min(value),max_value=max(value),Rsquared_mean=mean(Rsquared),Rsquared_var=var(Rsquared))


thiscutoff<-c(iso6cutoff$min_value,iso6cutoff$max_value)
isomap6cutoff_plot<-pdpFrame %>% filter(key%in% "iso6") %>%   mutate(key = factor(key, levels=candidates)) %>%  ggplot(pdpFrame,
       mapping = aes(x = value,
                           y = (yhat)))+
  geom_point(alpha=0.2)+
  geom_smooth(method = "loess", se=F)+
  theme_minimal()+geom_vline(xintercept = thiscutoff,size=2,color="firebrick4", linetype = "dashed")+xlab("Dimension 6")+ylab("PDP Value")

```

```{r}
### iso7
iso7_best25<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso7","yhat"])[5],"3rd Qu.:")))
iso7_best1<-as.numeric(str_squish(str_remove(summary(pdpFrame[pdpFrame$key%in%"iso7","yhat"])[6],"Max.   :"))) 
treshold<-(iso7_best1+iso7_best25)/2
iso7cutoff<-pdpFrame %>% filter(key%in% "iso7",yhat>treshold) %>% summarise(name="iso7",min_value=min(value),max_value=max(value),Rsquared_mean=mean(Rsquared),Rsquared_var=var(Rsquared))


thiscutoff<-c(iso7cutoff$min_value,iso7cutoff$max_value)
isomap7cutoff_plot<-pdpFrame %>% filter(key%in% "iso7") %>%   mutate(key = factor(key, levels=candidates)) %>%  ggplot(pdpFrame,
       mapping = aes(x = value,
                           y = (yhat)))+
  geom_point(alpha=0.2)+
  geom_smooth(method = "loess", se=F)+
  theme_minimal()+geom_vline(xintercept = thiscutoff,size=2,color="firebrick4", linetype = "dashed")+xlab("Dimension 7")+ylab("PDP Value")

```
### summarise

```{r}
library(patchwork)
save_summary<-isomap1cutoff_plot + isomap2cutoff_plot + isomap3cutoff_plot + isomap4cutoff_plot + isomap5cutoff_plot + 
   isomap6cutoff_plot + isomap7cutoff_plot +plot_layout(ncol = 2)
ggsave(save_summary,file="../figures/05_Shapley_cutoff_summaryplot.png",device = "png")

cutoff_dimensions<-rbind(iso1cutoff,iso2cutoff,iso3cutoff,iso4cutoff,iso5cutoff,iso6cutoff,iso7cutoff)
#cutoff_dimensions %>% fwrite("../output/07_cutoff_for_latenspace.csv")
```






# make correlation to see which part of the vactor are signficant for 2020 and 2021
