---
title: "06_figures_charts"
author: "Kolja Nenoff"
date: "2023-07-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# 1 Figure Methods dimred compare PCA ISO
## Load 01 data
```{r}

residual_sample_variances <- compute_if_no_file(
  get_data_file("residual_sample_variances.RDS"),
  make_residual_variance_lists,
  qual_comp_res = qual_comp_res,
  wdi_data_cons_df = wdi_data_cons_df,
  used_var_names = USED_VAR_NAMES,
  .overwrite = TRUE
)
```
### template
```{r}


pca_res <- residual_sample_variances$pca
iso_res <- residual_sample_variances$iso
median_res_var_pca <- residual_sample_variances$median_pca
median_res_var_iso <- residual_sample_variances$median_iso
hdi_res_var <- residual_sample_variances$hdi
```
```{r}
plot(pca_res[[1]],
   ylim = c(0, max_res_var_1),
   ## xlim = c(1, max_dim),
   xlim = c(1, 10),
   ylab = "residual variance",
   xlab = "number of dimensions",
   cex.lab = 2,
   las = 1,
   xaxt = "n",
   yaxt = "n",
   bty = "n",
   type = "n")

points(wdi_data_qual_cons_pca,      type = "b",
     lwd = 4, col = lighten("slategrey", 0.8))
points(wdi_data_qual_cons_iso[[2]], type = "b",
     lwd = 4, col = lighten("seagreen", 0.8))
text(1, wdi_data_qual_cons_pca[1],      "PCA",
   pos = 4, offset = 0.5, xpd = TRUE, cex = 2)
text(1, wdi_data_qual_cons_iso[[2]][1], "Ensemble Isomap",
   pos = 4, offset = 0.5, xpd = TRUE, cex = 2)
text(max_x + 0.75,         0.1, "10% Residual Variance", cex = 1.8,
   adj = c(1.1, -0.5), xpd = TRUE)
abline(h = 0.1, col = "gray50", lwd = 2)
par(las = 1, mgp = c(1.5, 0.75, 0))#, xpd = TRUE)
axis(side = 1, at = 1:10, labels = ifelse(1:10 %% 2 == 1, 1:10, ""),
   col = "gray50", col.axis = "gray50",
   cex.axis = 1.5, lwd = 1, tcl = -0.25, lwd.ticks = 2)
axis(side = 2, at = seq(0, 1, length.out = 6),
   col = "gray50", col.axis = "gray50",
   cex.axis = 1.5, lwd = 1, tcl = -0.25, lwd.ticks = 2)
```


# 2 Figure Linear estimation of the exmort
```{r}
require(broom)
dimred2021_knn250_2<-fread("../output/02_230612_Dimred_ExcessMort_annual.csv")
subset2020<-dimred2021_knn250_2 %>% filter(year%in% 2020) %>% select(year,iso1,iso2,iso3,iso4,iso5,iso6,iso7,iso8,iso9,iso10,year,P_mort_2020) %>% 
  rename(ExcessMort=P_mort_2020) %>% mutate(P_mort_2020=NULL)
subset2021<-dimred2021_knn250_2 %>% filter(year%in% 2021) %>% select(year,iso1,iso2,iso3,iso4,iso5,iso6,iso7,iso8,iso9,iso10,year,P_mort_2021) %>% 
  rename(ExcessMort=P_mort_2021) %>% mutate(P_mort_2020=NULL)

bothyears<-rbind(subset2020,subset2021)
e<-lm(ExcessMort~iso1+iso2+iso3+iso4+iso5+iso6+iso7+iso8+iso9+iso10+year,bothyears[]) 
e1<-lm(ExcessMort~iso1+iso2+iso3+iso4+iso5+iso6+iso7+iso8+iso9+iso10,bothyears[] %>% filter(year%in% 2020)) 
e2<-lm(ExcessMort~iso1+iso2+iso3+iso4+iso5+iso6+iso7+iso8+iso9+iso10,bothyears[] %>% filter(year%in% 2021)) 
e1_rsquared<-round(summary(e1)$r.squared,digits = 3)*100
e2_rsquared<-round(summary(e2)$r.squared,digits = 3)*100

e_plot2020<-ggcoef_model(e1)+ ggtitle(paste0("Isomap 2020; R\u00b2: ",e1_rsquared," %"))%>% suppressWarnings()
e_plot2021<-ggcoef_model(e2)+ ggtitle(paste0("Isomap 2021; R\u00b2: ",e2_rsquared," %")) %>%  suppressWarnings()
plotBoth<-ggarrange(e_plot2020,e_plot2021,common.legend = T,legend = "bottom") %>% suppressWarnings() 

ggsave("../figures/06_figures_Beta_plot.png",device = "png")
# annotate_figure(plotBoth, top = text_grob("Estimated betas for Isomap 2020 and 2021", 
#                color = "Slategray3", face = "bold", size = 12),bottom = text_grob("asd"))



models <- list(
  "Isomap 2020" = e1,
  "Isomap 2021" = e2
)
# ggcoef_compare(c(models),type = "faceted")+scale_color_viridis()
# ?ggcoef_compare
```

# 3 Figure Exmort types

```{r}
wdi_data_cons_df<-wdi_data_cons_df

featureList<-c("NY.GDP.PCAP.CD","Country Code","P_mort_2020","P_mort_2021","iso1","iso2","iso3","iso4","iso5","iso6","iso7","iso8","iso9","iso10","year","pscore_mean","RegionSoviet","Income Group")
```


## Plot gdp iso
```{r}
subset2020<-dimred2021_knn250_2 %>% filter(year%in% 2020) %>% select(any_of(featureList)) %>% rename(ExcessMort=P_mort_2020) %>%  mutate(P_mort_2020=NULL)
subset2021<-dimred2021_knn250_2 %>% filter(year%in% 2021) %>% select(any_of(featureList)) %>% rename(ExcessMort=P_mort_2021) %>% mutate(P_mort_2021=NULL)

bothyears<-rbind(subset2020,subset2021,use.names=FALSE)

wdi?

bothyears %>% filter(year%in% 2021) %>% mutate(Income_group=`Income Group`) %>% filter(!is.na(Income_group))%>% 
  mutate(Income_group = factor(Income_group, levels=c("High income",
                                      "Upper middle income",
                                      "Lower middle income",
                                      "Low income"
                                      )),`GDP per Capita (log)`=log(NY.GDP.PCAP.CD),
         `Isomap dimension 1`=iso1
         ) %>% 
  
   pivot_longer(names_to = "var",
               c("Isomap dimension 1","GDP per Capita (log)"),
               values_drop_na = TRUE) %>% 
  ggplot(aes(x=(value),y=ExcessMort,color=Income_group))+geom_point()+ theme_bw()+xlab("")+ylab("Excess Mortality") +scale_color_viridis(discrete = T)+facet_wrap(~var,scales = "free_x")+theme(legend.position = "bottom") 
ggsave("../figures/06_figures_GDP_Iso1.png",device = "png", width = 7, height = 5, dpi = 300, units = "in")
```
## Plot iso 2 

### check all the plots
```{r}

wdi_dimred_iso2 %>% filter(!is.na(iso2_all))%>%  mutate(maxdisthighlow=abs(iso2_0to25-iso2_50to75),
                                                        adjustvalue=iso2_75to100/maxdisthighlow) %>% arrange(desc(maxdisthighlow))-> subsetiso2

# for(i in 1:676){
# nameVar<-subsetiso2[i,"Series Code"] %>%  unlist
# applySD<-!is.na(dimred2021_knn250_2[,..nameVar]) %>%  unlist
# 
# wool<-dimred2021_knn250_2[applySD[,1]] %>% filter(year%in% 2010:2021) %>% filter(!is.na(iso2)) %>% 
# ggplot(aes_string(x="iso2",y=paste(nameVar)))+geom_point()
# wool %>% ggsave(file = paste0("../test/run",i,".png",sep=""),device = "png")
# }

```
#### candidates
```{r}
iso2_candidates<-c(5,15,21,26,27,32,49,57,66,68,70,71,80,97,102,119,123,180,207,377,383,407,439,583)
nameVar_iso2_candidates<-subsetiso2[iso2_candidates,"Series Code"] 

for(i in iso2_candidates){
nameVar<-subsetiso2[i,"Series Code"] %>%  unlist
applySD<-!is.na(dimred2021_knn250_2[,..nameVar]) %>%  unlist

wool<-dimred2021_knn250_2[applySD[,1]] %>% filter(year%in% 2010:2021) %>% filter(!is.na(iso2))


wool %>%  mutate(categorie=case_when(scale(iso2)>1.5~"Iso2 peak  high",
                                                 scale(iso2)<  -0.5~"Iso2 peak  Low",
                                                 (scale(iso2)> (-0.5) &scale(iso2)<1.5)~"normal",
                                                  TRUE~"a"
                                                  ))%>% 
  filter(!is.na(get(nameVar)),!is.na(categorie)) -> yo


yo$categorie<-factor(as.factor(yo$categorie),levels=c("Iso2 peak  Low","normal","Iso2 peak  high","a"))
yo2<-yo[,colnames(yo)[colnames(yo)%in% c(paste(nameVar),"categorie")],with=F]
colnames(yo2)[1]<-"value"
series_label<-wdi_explained[wdi_explained$`Series Code` %in% nameVar,"Indicator Name"]

wool2<-ggstatsplot::ggbetweenstats(
  plot.type = "boxviolin",
                            p.adjust.method = "BH",
        point.args = list(alpha = 0),

      data = yo2,
      x = categorie,
      y = value ) + 
      # Add labels and title
      labs(x="",
           y = nameVar,
           title = series_label
      )+theme(
        # This is the new default font in the plot
        text = element_text(family = "Roboto", size = 10, color = "black"),
        plot.title = element_text(
          family = "Lobster Two", 
          size = 14,
          face = "bold",
          color = "#2a475e"
        ),
        # # Statistical annotations below the main title
        plot.subtitle = element_text(
          family = "Roboto",
          face = "bold",
          color="#1b2838"
        ),
        plot.title.position = "plot", # slightly different from default
        axis.text = element_text(size = 10, color = "black"),
        axis.title = element_text(size = 12)
      )

wool2 %>% ggsave(file = paste0("../figures/06_iso2plots/",i,".png",sep=""),device = "png")
}

```

### plots
```{r}
featureList<-c("VC.IHR.PSRC.MA.P5","TM.VAL.MRCH.R3.ZS","TX.VAL.MRCH.R2.ZS","SP.DYN.CDRT.IN","SP.POP.2024.FE.5Y","Country Code","P_mort_2020","P_mort_2021","iso1","iso2","iso3","iso4","iso5","iso6","iso7","iso8","iso9","iso10","year","pscore_mean","RegionSoviet","Income Group")
subset2020<-dimred2021_knn250_2 %>% filter(year%in% 2020) %>% select(any_of(featureList)) %>% rename(ExcessMort=P_mort_2020) %>%  mutate(P_mort_2020=NULL)
subset2021<-dimred2021_knn250_2 %>% filter(year%in% 2021) %>% select(any_of(featureList)) %>% rename(ExcessMort=P_mort_2021) %>% mutate(P_mort_2021=NULL)

bothyears<-rbind(subset2020,subset2021,use.names=FALSE)

#
# 
# ggsave("../figures/06_figuressa_GDP_Iso1.png",device = "png", width = 7, height = 5, dpi = 300, units = "in")
```
```{r}
bothyears %>% filter(year%in% 2019:2021) %>% mutate(Income_group=`Income Group`) %>% filter(!is.na(Income_group)) %>% 
  ggplot(aes(x=(iso2),y=log(SP.DYN.CDRT.IN)))+geom_point()+geom_smooth(method = "gam")+ theme_bw()+xlab("Dimension 2")+ylab("Death rate, crude (per 1,000 people)") +scale_color_viridis(discrete = T) 



bothyears %>% filter(year%in% 2019:2021) %>% mutate(Income_group=`Income Group`) %>% filter(!is.na(Income_group)) %>% 
  ggplot(aes(x=(iso2),y=log(VC.IHR.PSRC.MA.P5)))+geom_point()+geom_smooth(method = "lm")+ theme_bw()+xlab("Dimension 2")+ylab("Death rate, crude (per 1,000 people)") +scale_color_viridis(discrete = T) 
```
```{r}
bothyears %>% filter(year%in% 2019:2021) %>% mutate(Income_group=`Income Group`) %>% filter(!is.na(Income_group)) %>% 
  ggplot(aes(x=(iso2),y=TM.VAL.MRCH.R3.ZS))+geom_point()+geom_smooth(method = "gam")+ theme_bw()+xlab("Dimension 2")+ylab("Merchandise imports from low- and middle-income economies in Latin America & the Caribbean (% of total merchandise imports)") +scale_color_viridis(discrete = T) 
bothyears %>% filter(year%in% 2019:2021) %>% mutate(Income_group=`Income Group`) %>% filter(!is.na(Income_group)) %>% 
  ggplot(aes(x=(iso2),y=TX.VAL.MRCH.R2.ZS))+geom_point()+geom_smooth(method = "gam")+ theme_bw()+xlab("Dimension 2")+ylab("Merchandise exports to low- and middle-income economies in Europe & Central Asia (% of total merchandise exports)") +scale_color_viridis(discrete = T) 
```

